name: Reusable Git Secrets Scan

on:
    workflow_call:
jobs:
    secret-scan:
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set Execution Policy for PowerShell
              run: Set-ExecutionPolicy Bypass -Scope Process -Force

            - name: Run Powershell Instalation Script
              run: scripts/script.ps1
