name: "test"

on:
  pull_request:
  push:
    branches:
      - main
      - develop
  
jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            # - name: Set Execution Policy for PowerShell
            #   run: Set-ExecutionPolicy Bypass -Scope Process -Force

            - name: Install git-secrets
              run: |
                git clone https://github.com/awslabs/git-secrets.git
                cd git-secrets
                sudo make install
                echo "git-secrets instaled"

            # - name: Run Powershell Instalation Script
            #   run: scripts/script.ps1

            - name: Configure git-secrets
              run: |
                git secrets --install
                git secrets --add "juice"

            - name: Scan Only Changed File for Secrets
              run: |
                git diff --name-only ${{ github.event.befor }} ${{ github.sha }} > changed_files.txt
                if [ -s changed_files.txt ]; then
                  git secrets --scan $(cat changed_files.txt)
                else
                  echo "No files changed. Skipping secret scan."
                fi

            - name: Fail if Secrets Are Found
              if: failure()
              run: |
                echo "Error: Secrets detected"
                exit 1

            # - name: Scan for secrets
            #   run: |
            #     git secrets --scan
            #   continue-on-error: false

            # - name: Fail if Secrets Are Found
            #   run: |
            #     if ($LASTEXITCODE -ne 0) {
            #         Write-Host "Error: secrets detected"
            #         exit 1
            #         }

