name: "Block PRs with Restricted Words in Files"

on:
  pull_request:
    types:  [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  
jobs:
    check-restricted-files:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            # - name: Set Execution Policy for PowerShell
            #   run: Set-ExecutionPolicy Bypass -Scope Process -Force

            - name: Install git-secrets
              run: |
                git clone https://github.com/awslabs/git-secrets.git
                cd git-secrets
                sudo make install
                echo "git-secrets instaled"

            # - name: Run Powershell Instalation Script
            #   run: scripts/script.ps1

            - name: Configure git-secrets
              run: |
                git secrets --install
                git secrets --add "juice"

            - name: Get List of Changed Files
              id: changed-files
              run: |
                git fetch origin ${{ github.base_ref }} --depth=1
                git diff --name-only origin/${{ github.base_ref }} | grep -v '^.github/workflows/test.yml$' > changed_files.txt
                echo "Changed files"
                cat changed_files.txt
                echo "CHANGED_FILES=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV
            
            - name: Scan Changed Files with git-secrets
              id: git-secrets-check
              run: |
                CHANGED_FILES=$(cat changed_files.txt)

                if [ -z "$CHANGED_FILES" ]; then
                  echo "No files changed. Skipping git-secrts scan"
                  exit 0
                fi

                echo "Scanning changed files for secrets..."
                for FILE in $CHANGED_FILES; do
                 if [ -f "$FILE" ]; then
                   if ! git secrets --scan "$FILE"; then
                     echo "ERROR: Secrets detected in $FILE"
                     exit 1
                   fi
                 fi
                done

                echo "No Secrets found"

            # - name: Auto-Close PR If Secrets Found
            #   if: failure()
            #   uses: actions/github-script@v6
            #   with:
            #     github-token: ${{ secrets.GITHUB_TOKEN}}
            #     script: |
            #        const prNumber = context.payload.pull_request.number;
            #        const repoOwner = context.repo.owner;
            #        const repoName = context.repo.repo;

            #        console.log("closing PR")

            #         await github.rest.pulls.update({
            #           owner: repoOwner,
            #           repo: repoName,
            #           pull_number: prNumber,
            #           state: "closed"
            #         });
            

